name: Deploy spring code to aws elastic beanstalk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: build with gradlew
        run: ./gradlew clean bootJar

      - name: upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/demo-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DemoJavaApp
          environment_name: DemoJavaApp-env
          version_label: demo-2023.Jul.${{github.run_attemp}}
          region: ap-southeast-2
          deployment_package: demo-0.0.1-SNAPSHOT.jar